### ISSUE TITLE
hydromt: setup manholes

### ISSUE THREAD

**Issue by rhutten** [Deltares/HYDROLIB#12]
**Tasks**
- setup_functions to  manholes.py
- setup-functions to dflowfm.py
- specific functions of preprocess to manholes.py
- common function stay in preprocess

**Requirements**
- docstrings
- documentation

**Comment by veenstrajelmer** [comment]
This issue will be closed as won't do since [hydromt_delft3dfm](https://github.com/Deltares/hydromt_delft3dfm) moved to a separate repos.
