### ISSUE TITLE
allow multiple type of crossections, e.g. branch+ point + xyz

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB#122]
This is allowed by the user specifying a list of filenames and a list of crosssection types in the ini file.

**Comment by xldeltares** [comment]
The test in GUI failed. reopen for inverstigation.

**Comment by xldeltares** [comment]
Improvement from SantaCruz: crosssections documentation is not clear. Do we need certain str attribute values to be case insenstive? e.g. branchType River and river

**Comment by veenstrajelmer** [comment]
This issue will be closed as won't do since [hydromt_delft3dfm](https://github.com/Deltares/hydromt_delft3dfm) moved to a separate repos.
