### ISSUE TITLE
a new function to create 1d2d links on boundary nodes

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB#128]
**Is your feature request related to a problem? Please describe.**
Currently the 1d_to_2d function will not setup 1d2d links at the boundaries. This is desired for river systems where boundaries have boundary conditions. However, We use hydromt-delft3dfm for setting up both river and pipe systems. In a pipe system, most of the time, a "boundary node" is no different than other nodes, which can interact with 2D layer. There are indeed exceptions where a downstream boundary node (an outlet) has a boundary condition representing a water level, but we should allow the user to decide whether they want 1D2D links at these exception locations.

**Describe the solution you'd like**
for now the functions to setup 1d_to_2d are:
links1d2d_add_links_1d_to_2d
We probably need another one:
mesh.links1d2d_add_links_1d_to_2d_include_boundary

**Describe alternatives you've considered**
Attempted to use the following function to add missing boundary links:
```
 # generate 1d2d links #FIXME does not work yet
    network._link1d2d.meshkernel.contacts_compute_boundary(node_mask=node_mask, polygons=geometrylist, search_radius = max_length * 10)
    network._link1d2d._process()
```

**Additional context**
Whether this function needs to be in hydrolib or hydrolib-core.

**Comment by xldeltares** [comment]
![image](https://user-images.githubusercontent.com/71022080/200584121-d7e516e5-f22e-402b-918c-cda84fa2885d.png)

**Comment by veenstrajelmer** [comment]
This issue will be closed as won't do since [hydromt_delft3dfm](https://github.com/Deltares/hydromt_delft3dfm) moved to a separate repos.
