### ISSUE TITLE
Setup crosssection from branch

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB#130]
Setup crosssection from branch needs further improvement (potential new implementation from SantaCruz 1D2D branch):
- [x] switch rectangle crs to zw crs
- [x] create a separate function for circle profile

**Comment by veenstrajelmer** [comment]
This issue will be closed as won't do since [hydromt_delft3dfm](https://github.com/Deltares/hydromt_delft3dfm) moved to a separate repos.
