### ISSUE TITLE
Bug: inifields file path incorrect.

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB#137]

**Comment by xldeltares** [comment]
DiskOnlyFileModel in hydrolib-core does not resolve path correctly. Cannot set anchor or parent path. to be discussed.

**Comment by veenstrajelmer** [comment]
This issue will be closed as won't do since [hydromt_delft3dfm](https://github.com/Deltares/hydromt_delft3dfm) moved to a separate repos.
