### ISSUE TITLE
update maps from an existing 2D model does not work well

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB#138]
**Describe the bug**
When adding a new map layer to an existing 2D model, existing maps of the 2D model cannot be read and written correctly. new map layer overwrites the existing map layers. 

**To Reproduce**
Step 1. Build a 2D model with bedlevel only, check the fieldfile.ini, bedlev is written and correct; 
Step 2. Update the model with a friction layer, check the fieldfile.ini, friction is added correctly but bedlev is gone.
The ini files used are attached. [test.zip](https://github.com/Deltares/HYDROLIB/files/10195006/test.zip)

**Comment by hboisgon** [comment]
Issue posted in hydromt: https://github.com/Deltares/hydromt/issues/256

**Comment by veenstrajelmer** [comment]
This issue will be closed as won't do since [hydromt_delft3dfm](https://github.com/Deltares/hydromt_delft3dfm) moved to a separate repos.
