### ISSUE TITLE
HydroMT: have both 1D and 2D in mesh component

### ISSUE THREAD

**Issue by hboisgon** [Deltares/HYDROLIB#141]
So far, we use self.mesh for the 2D mesh and self.branches for 1D (GeoDataFrame) and self.dfmmodel.netfile.network._mesh1d.
Ideally all mesh components should be contained into self.mesh and we should use xugrid / meshkernel functions for every mesh manipulations without having to use hydrolib-core classes in between.

This requires the following changes:

- adapt setup_mesh
- adapt write_mesh
- self.mesh1d should be derived from self.mesh usig xugrid
- adapt self.set_mesh1d: this requires rewritting mesh1d_add_branch to avoid using hydrolib-core class and meshkernel/xugrid functions directly and updating self.mesh instead of self.dfmmodel
- self.network1d_nodes
- self.mesh2d
- self.set_mesh2d
- self.branches to be derived from self.mesh with xugrid

**Comment by xldeltares** [comment]
update: xugrid now supports mesh1d

**Comment by veenstrajelmer** [comment]
This issue will be closed as won't do since [hydromt_delft3dfm](https://github.com/Deltares/hydromt_delft3dfm) moved to a separate repos.
