### ISSUE TITLE
HydroMT: recognizing branch types

### ISSUE THREAD

**Issue by hboisgon** [Deltares/HYDROLIB#142]
In HydroMT, to facilitate model building from different data sources, we distinguish several types of 1D branches:

- rivers
- channels
- pipes
- tunnels

While this is useful for model building, delft3d-fm does not recognize these types (only channel and pipe but this only a GUI file).
This means that reading this information back in model update is not straightforward.

Would there still be a way to make the distinction or should we abandon it within hydromt and stick to channel/opensystem and pipe/closedsystem ?

**Comment by veenstrajelmer** [comment]
This issue will be closed as won't do since [hydromt_delft3dfm](https://github.com/Deltares/hydromt_delft3dfm) moved to a separate repos.
