### ISSUE TITLE
implement 2d boundary

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB#152]
Functional requirement:
- [x]  spatially-uniform constant boundary using ``boundaries_fn`` and ``boundary_value`` (default), --> ~~But this DOES NOT open in GUI.~~ --> by writing into a timeseries with start stop time the same as model time, this can be open in GUI.
- [x] spatially-uniform time-series boundary read from ``boundaries_fn`` and ``boundaries_timesries_fn``  (TODO Not Implemented),
- [x]  spatially-varying time-series boundary read from ``boundaries_geodataset_fn`` (TODO Not Implemented).

Remarks:

- [x] ~~Hydrolib-core polyfile parser was not applicable for boundary type pli file~~. Bug reported here: https://github.com/Deltares/HYDROLIB-core/issues/467 --> It turns out the point labels exported by GUI is not used by the kernel, therefore no need to support this. See comment in the issue. 
- [x] ~~Above also means we cannot use hydrolib-core to correctly read it back.~~ --> Because of the above, this is no longer valid, hydrolib-core can read it back.
- [x] Write_forcings does not yet support complete writing of boundary, meteo and laterals, needs improvement. New feature requested here:  https://github.com/Deltares/HYDROLIB/issues/153 --> half fixed for 1d and 2d boundary
- [ ] Need more inverstigation on how to read everything back properly.

**Comment by xldeltares** [comment]
First option is implemented.

**Comment by veenstrajelmer** [comment]
This issue will be closed as won't do since [hydromt_delft3dfm](https://github.com/Deltares/hydromt_delft3dfm) moved to a separate repos.
