### ISSUE TITLE
hydromt data adaptor wrapper to read geodataframe 

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB#21]
hydromt data adaptor wrapper to read geodataframe that satisfies the need for dflowfm

steps:
1. add additional kwargs in data catalogue yml file.
2. parse kwargs and apply additional functions accordingly.

adapted /added functions include:
1. customised clipping based on clip_buffer and clip_predicate
2. retyping based on retype
3. slicing based on required_columns and required_query

**Comment by veenstrajelmer** [comment]
This issue will be closed as won't do since [hydromt_delft3dfm](https://github.com/Deltares/hydromt_delft3dfm) moved to a separate repos.
