### ISSUE TITLE
adapt to poetry

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB#23]

**Comment by hboisgon** [comment]
Properly adding hydromt as dependency via poetry seems a bit complex. 
@evetion or @BeardedPlatypus could one of you have a look at it? You can work in the hydromt branch for this.

Many thanks!

**Comment by evetion** [comment]
Are there problems when you do `poetry add hydromt`?

**Comment by hboisgon** [comment]
Yes... there's a new version of netcdf4 1.6.0 that hydrolib-core restricts. So for now first need to add netcdf==1.57 to hydrolib. Later it still fails to properly link fiona to gdal and this I could not solve

**Comment by veenstrajelmer** [comment]
This issue will be closed as won't do since [hydromt_delft3dfm](https://github.com/Deltares/hydromt_delft3dfm) moved to a separate repos.
