### ISSUE TITLE
Generate 2D Mesh

### ISSUE THREAD

**Issue by grongen** [Deltares/HYDROLIB#34]
Generate 2D Mesh using MeshKernelPy

Requirement:
- Generate rectangular mesh
- Clip by polygon (taking into account holes)
- Mesh refinement,: pecify an area (polygon) in which the mesh is refined N times.
- 
Wish:
- Rotate grid
- Variable x or y scale (for example, to make a rectangular grid in lat lon)
- Generate triangular grids.
- Deriving raster statistics, for example to derive terrain heights.

**Comment by rhutten** [comment]
@grongen Is only the mesh refinement missing?  Or are there still other requirements left-to-do? And do we also want to work with orthogonalization?

**Comment by grongen** [comment]
The mesh refinement is implemented, but is not processed for some reason (is does work in the test). I'll check that next week.

The wishes:
- Rotate grid
- Variable x or y scale (for example, to make a rectangular grid in lat lon)
- Deriving raster statistics, for example to derive terrain heights.
Are not implemented yet. The last one I'll copy from delft3dfmpy (for elevation), the others are not needed for finishing this issue IMO.

**Comment by rhutten** [comment]
@grongen for Deriving raster statistics, it could be useful to see which functions are already implemented in HydroMT. @hboisgon Could you give a direction where these functions are given?

**Comment by hboisgon** [comment]
We do not really have mesh handling yet in HydroMT but would like to support it. Prbably going to be a mix of methods from our regular grid object (Raster xarray) https://deltares.github.io/hydromt/latest/api.html#raster-methods (method reproject_like or zonal_statistics/sample). We may also use and extend our Geodataset object  (xarray based on points only for now but could be polygon). We have some methods there as well based on internal transformation from xarray to geodataframe (https://deltares.github.io/hydromt/latest/api.html#geospatial-timeseries-methods). Happy to brainstorm together on the subject

**Comment by veenstrajelmer** [comment]
This issue will be closed as won't do since [hydromt_delft3dfm](https://github.com/Deltares/hydromt_delft3dfm) moved to a separate repos.
