### ISSUE TITLE
Link bvetween closedwater system + openwater system

### ISSUE THREAD

**Issue by hboisgon** [Deltares/HYDROLIB#70]
Connecting closedwater system and openwater system by connecting where intersecting

**Comment by xldeltares** [comment]
The current implementation includes linking of new branches into existing branches at the outlet of the new branches.

a closed system has only a downstream outlet
an open system has both upstream and downstream outlets.

when adding a new branch type:
1. first check if an open system exists. 
2. snap the outlets into the existing network's computational nodes.
3. split the existing network at the computational nodes
