### ISSUE TITLE
Setup manholes

### ISSUE THREAD

**Issue by hboisgon** [Deltares/HYDROLIB#71]
Add manholes on top of pipes based on pipe locations (pipe end) or by location dataset, inc manholes characteristics (size...)

Use closed or open manholes depending on 1D (open) or 1D2D (closed)

**Comment by xldeltares** [comment]
Manholes can be set by the following method
- [ ] get dimensions from a constant set or from a table based on pipe diameter.
- [ ] get street level from dem
- [ ] get manhole dimensions from user-defined dataset

**Comment by xldeltares** [comment]
Pull request #82 is created. Will test the following:
- [x] 1. global data with default manholes
- [ ] 2. 1+ manholes from dem
- [ ] 3. test example with user manholes
- [ ] 4. 3+ manholes from dem

**Comment by xldeltares** [comment]
TODO: branches.gui file is needed to display pipes and manholes correctly in GUI. #83

**Comment by xldeltares** [comment]
TODO: set usestreetstorage = False when setting up 1D2D links. (#72 )
