### ISSUE TITLE
Add grid refinement

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB#88]

**Comment by xldeltares** [comment]
@rhutten for now hydrolib-core only supports refine based on polygon (function is called ```refine``` in hydrolib-core, which calls function ```mesh2d_refine_based_on_polygon``` in meshkernelpy. Do we need to support also refine based on samples? hydrolib-core does not have this option yet, but it is possible in meshkernelpy using function ```mesh2d_refine_based_on_samples```. 

Work will include implementation in both hydrolib and hydrolib-core.

**Comment by rhutten** [comment]
@xldeltares, I think it would be good to add that. Mesh refinement with polygon becomes more difficult if you want to refine some parts twice and other part thrice. By creating a sample raster on forehand, you can do it once. Let's discuss this together next week.

**Comment by xldeltares** [comment]
Mesh refinement based on samples is implemented. 

The issue still has some points to discuss:
- whether to use refine function as ```setup_mesh2d_refine``` function, or as a workflow in ```setup_mesh2d```.  The latter has the benefit of making sure the refine is applied right after a regular mesh2d is created but will make the function bulker.  Besides, if this is a workflow, where should we put it? in the current hydamo mesh workflows or create a seperate one? Maybe latter is better suited considering we are moving towards a new repo. 
- whether to use the refine based on polygon from hydamo and hydrolib-core as is.  The current refine function in hydrolib-core is a much simplified version with hard-coded parameters which do not yield satisfactory results. But still use it makes the code more consistant with hydrolib-core build in function

**Comment by veenstrajelmer** [comment]
This issue will be closed as won't do since [hydromt_delft3dfm](https://github.com/Deltares/hydromt_delft3dfm) moved to a separate repos.
