### ISSUE TITLE
Branch order not passed when creating mesh1d from branches

### ISSUE THREAD

**Issue by xldeltares** [Deltares/HYDROLIB#94]

**Comment by xldeltares** [comment]
After changing branch order to 1 for all rivers this following error appears
![image](https://user-images.githubusercontent.com/71022080/187920208-a38c8f4e-bf12-48b6-a1c4-3f76cf39c68d.png)

**Comment by xldeltares** [comment]
Interestingly, dimr outside of GUI runs fine

**Comment by xldeltares** [comment]
TODO:
branch order is not written to netcdf file
river has no computational nodes
river crosssection is not fully correct
pipe river connection might need further looking into

**Comment by veenstrajelmer** [comment]
This issue will be closed as won't do since [hydromt_delft3dfm](https://github.com/Deltares/hydromt_delft3dfm) moved to a separate repos.
